# Perceptron XOR 

In [ ]:
def multiplicação(x,w):
    return np.sum(np.multiply(x,w))

In [164]:
import random as rd
import numpy as np

ativacao = lambda x: 0 if x < 0 else 1

dataset = [
    (array([0,0,0.4]), 0),
    (array([0,1,0.4]), 1),
    (array([1,0,0.4]), 1),
    (array([1,1,0.4]), 1),
]

w = np.random.rand(2,3)
erro = []
eta = 0.4
n = 200

for i in range(n):
    x, esperado = rd.choice(dataset)
    resultado = multiplicação(w, x)
    erros = esperado - ativacao(resultado)
    erro.append(erros)
    w += eta * erros * x

for x, _ in training_data:
    resultado = multiplicação(x, w)
    print("{}: {} -> {}".format(x[:2], resultado, unit_step(resultado)))

[0. 0.]: -0.09708306529640494 -> 0
[0. 1.]: 0.39491804489549914 -> 1
[1. 0.]: 1.7986106620241011 -> 1
[1. 1.]: 2.290611772216005 -> 1
